# Generated by Django 4.2.6 on 2023-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joblist_contract_type_alter_joblist_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='contract_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Project', 'Project'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
