# Generated by Django 4.2.6 on 2023-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_joblist_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='compensation',
            field=models.CharField(choices=[('Equity', 'Equity'), ('Health insurance', 'Health insurance'), ('Phantom shares', 'Phantom shares'), ('Paid time off', 'Paid time off')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblist',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CNY', 'CNY')], max_length=50),
        ),
    ]
