# Generated by Django 4.2.6 on 2023-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joblist_compensation_alter_joblist_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
