# Generated by Django 4.2.6 on 2023-12-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_joblist_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('inactive', 'Inactive')], default='draft', max_length=10),
        ),
    ]
