# Generated by Django 4.2.6 on 2023-12-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_joblist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='business',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblist',
            name='role',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblist',
            name='share',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joblist',
            name='compensation',
            field=models.CharField(max_length=100),
        ),
    ]
