# Generated by Django 4.2.6 on 2023-12-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_joblist_business_joblist_role_joblist_share_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='joblist',
            name='compensation',
        ),
        migrations.AddField(
            model_name='joblist',
            name='compensation',
            field=models.ManyToManyField(to='jobs.compensation'),
        ),
    ]
