# Generated by Django 4.2.6 on 2023-12-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_compensation_remove_joblist_compensation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compensation',
            new_name='CompensationsList',
        ),
    ]
