# Generated by Django 4.2.6 on 2023-12-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_compensation_compensationslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='contract_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Project', 'Project'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
