# Generated by Django 4.2.6 on 2023-12-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_joblist_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefitslist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
