# Generated by Django 4.2.7 on 2024-01-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_benefitslist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='business',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('CAD', 'CAD'), ('CNY', 'CNY')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='maximum_salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='minimum_salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='share',
            field=models.TextField(blank=True, null=True),
        ),
    ]
