# Generated by Django 4.2.7 on 2024-01-09 18:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='HRTalks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HRTalks',
                'verbose_name_plural': 'HRTalks',
            },
        ),
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2)),
                ('video', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HelpCenter',
                'verbose_name_plural': 'HelpCenter',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guide',
            },
        ),
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('introduction', ckeditor.fields.RichTextField(blank=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PU', 'Published')], default='DR', max_length=2)),
                ('category', models.CharField(choices=[('cat1', 'Tips & Tricks'), ('cat2', 'How-to'), ('cat3', 'Technology'), ('cat4', 'Talent')], default='cat1', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
