# Generated by Django 4.2.7 on 2024-01-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='helpcenter',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='hrtalks',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='cover',
            field=models.URLField(blank=True),
        ),
    ]
