# Generated by Django 4.2.7 on 2024-01-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_alter_blog_author_alter_guide_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Tips & Tricks', 'Tips & Tricks'), ('How-to', 'How-to'), ('Technology', 'Technology'), ('Talent', 'Talent')], default='cat1', max_length=100),
        ),
    ]
