# Generated by Django 4.2.7 on 2024-01-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0005_blogcategory_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='category',
            field=models.CharField(choices=[('Tips & Tricks', 'Tips & Tricks'), ('How-to', 'How-to'), ('Technology', 'Technology'), ('Talent', 'Talent')], default='Tips & Tricks', max_length=100),
        ),
    ]
