# Generated by Django 4.2.7 on 2024-01-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_alter_blogcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
