# Generated by Django 4.2.7 on 2024-01-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0007_remove_blogcategory_category_blogcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='resource',
            field=models.URLField(blank=True, null=True),
        ),
    ]
