# Generated by Django 4.2.7 on 2024-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0008_guide_pdf_guide_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alt_cover',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contentsection',
            name='alt_image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='guide',
            name='alt_cover',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='helpcenter',
            name='alt_cover',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hrtalks',
            name='alt_cover',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='alt_cover',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='research',
            name='alt_cover',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
