# Generated by Django 4.2.7 on 2024-01-29 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0009_blog_alt_cover_contentsection_alt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='guide',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='helpcenter',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hrtalks',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='research',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
