# Generated by Django 4.2.7 on 2024-01-29 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0010_blog_date_up_guide_date_up_helpcenter_date_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guide',
            name='date_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='helpcenter',
            name='date_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hrtalks',
            name='date_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='research',
            name='date_up',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
