# Generated by Django 5.0.3 on 2024-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0011_alter_blog_date_up_alter_guide_date_up_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Help Category",
                "verbose_name_plural": "Help Categories",
            },
        ),
        migrations.RenameModel(
            old_name="News",
            new_name="Wiki",
        ),
        migrations.AlterModelOptions(
            name="wiki",
            options={"verbose_name": "Wiki", "verbose_name_plural": "Wiki"},
        ),
        migrations.DeleteModel(
            name="HRTalks",
        ),
    ]
