# Generated by Django 4.2.7 on 2024-01-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getqoute',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='getqoute',
            name='tool',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
