# Generated by Django 4.2.7 on 2024-01-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_getqoute_phone_alter_getqoute_tool'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetQoute',
            new_name='GetQuote',
        ),
    ]
