# Generated by Django 4.2.7 on 2024-01-18 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_rename_getqoute_getquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=200)),
                ('last', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('companyName', models.CharField(max_length=200)),
                ('companyWebsite', models.URLField()),
                ('companySize', models.CharField(max_length=200)),
                ('interest', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
