# Generated by Django 4.2.7 on 2024-02-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('Most of my work is recruitment', 'Most of my work is recruitment'), ('I lead recruitment teams', 'I lead recruitment teams'), ("I'm an HR leader", "I'm an HR leader"), ('I work in the HR world', 'I work in the HR world'), ("I'm a business leader", "I'm a business leader"), ("I'm none, but super curious", "I'm none, but super curious")], max_length=50)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('I need help using ClousH', 'I need help using ClousH'), ('I need help with my account', 'I need help with my account'), ('I need to report an issue', 'I need to report an issue')], max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='support_images/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
