# Generated by Django 4.2.7 on 2024-02-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_contactsale_feedbackmessage_support_waitlistemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackMessage',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
