# Generated by Django 5.0.3 on 2024-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0006_delete_feedbackmessage_delete_support"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GetQuote",
        ),
        migrations.AddField(
            model_name="contactsale",
            name="first",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactsale",
            name="last",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactsale",
            name="message",
            field=models.TextField(default=0, max_length=450),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactsale",
            name="reason",
            field=models.CharField(
                choices=[
                    (
                        "Most of my work is recruitment",
                        "Most of my work is recruitment",
                    ),
                    ("I lead recruitment teams", "I lead recruitment teams"),
                    ("I'm a business leader", "I'm a business leader"),
                    ("I'm just super curious", "I'm just super curious"),
                ],
                max_length=50,
            ),
        ),
    ]
