# Generated by Django 4.2.6 on 2024-03-10 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0007_delete_getquote_contactsale_first_contactsale_last_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsale",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contactsale",
            name="reason",
            field=models.CharField(
                choices=[
                    (
                        "Most of my work is recruitment",
                        "Most of my work is recruitment",
                    ),
                    ("I lead recruitment teams", "I lead recruitment teams"),
                    ("I'm a business leader", "I'm a business leader"),
                    ("I'm just super curious", "I'm just super curious"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 10, 17, 35, 22, 583452, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
