# Generated by Django 4.2.6 on 2024-03-10 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0008_alter_contactsale_email_alter_contactsale_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 10, 18, 0, 46, 436934, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
