# Generated by Django 4.2.6 on 2024-03-10 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0009_alter_resource_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 10, 18, 1, 7, 822155, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
