# Generated by Django 4.2.2 on 2023-06-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0002_emailregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRegister',
        ),
    ]
