# Generated by Django 4.2.2 on 2023-06-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0003_delete_emailregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
