# Generated by Django 4.2.6 on 2023-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Feedback',
            new_name='ContactSale',
        ),
        migrations.RenameModel(
            old_name='WaitlistEntry',
            new_name='WaitlistEmail',
        ),
    ]
