# Generated by Django 4.2.7 on 2024-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_feedbackmessage_rename_feedback_contactsale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('I need help using ClousH', 'I need help using ClousH'), ('I need help with my account', 'I need help with my account'), ('I need to report an issue', 'I need to report an issue')], max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='support_images/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
