# Generated by Django 4.2.2 on 2023-06-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_post_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='yes_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
