# Generated by Django 4.2.2 on 2023-06-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_no_votes_post_yes_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='yes_votes',
        ),
    ]
