import { Toaster } from '@/components/ui/toaster'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Metrics from '@/metrics'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Mensaje visible solo en pantallas menores a 'lg' */}
        <div className="lg:hidden text-center bg-blue-100 text-blue-800 fixed inset-0 z-50 flex items-center justify-center">
          <p>This content is only available on laptop screens and larger devices.</p>
        </div>

        {/* Contenido principal visible solo en pantallas 'lg' o mayores */}
        <main className='hidden lg:block h-full w-full'>
          {children}
          <Metrics />
        </main>
        <Toaster/>
      </body>
    </html>
  )
}
