# Generated by Django 4.2.7 on 2024-01-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromularios', '0002_contacto_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='subject',
            field=models.CharField(choices=[('Request live demo', 'Request live demo'), ('Contact sales', 'Contact sales'), ('Redeem sign up code', 'Redeem sign up code'), ('Onboarding aid', 'Onboarding aid'), ('1:1 consulting sessions', '1:1 consulting sessions'), ('Paid pilot', 'Paid pilot')], max_length=50),
        ),
    ]
