import Navbar from "components/navigation/Navbar";
import Footer from "components/navigation/Footer";
import Layout from "hocs/layouts/Layout";
import icon from "assets/img/favicon.png";
import { Helmet} from "react-helmet-async";
import { useEffect } from "react";
import mixpanel from "mixpanel-browser";
import Logo from "components/navigation/FixedLogo";

function Terms() {
  useEffect(() => {
    window.scrollTo(0, 0);
    mixpanel.track("Privacy Page", {
      Type: 'Privacy',

    });
  }, []);
  mixpanel.track("Privacy Page");
  return (
    <Layout>
      <Helmet>
      <meta name="robots" content="noindex" />
      <link rel="icon" content={icon} />
        <meta name="author" content="Clous Technology SL" />
        <meta name="publisher" content="Clous" />
        <meta property="og:image" content='https://clous.s3.eu-west-3.amazonaws.com/images/ClousPeer.webp' />
        </Helmet>
        <div className="bg-[#FAFAFA] text-dark-blue-greenish text-sm font-semibold max-w-8xl px-4 sm:px-6 xl:px-16 2xl:px-24 flex-wrap w-full fixed z-30  ">

<Navbar />             
</div>
<div className="z-40 relative">
        <Logo />
      </div>
      <div className="pt-28 px-6">
        <div className="relative ">
        <h1
              className="text-4xl font-bold tracking-tight text-button-orange
               sm:text-5xl lg:text-6xl"
            >
              {" "}
              Terms of use
            </h1>
         
        </div>
        <div className="lg:max-w-6xl mx-auto my-6 text-xl">
        <p>
        Thank you for using Clous!

These Terms of Use apply to your use of Clous Peer, ClousH and other Clous services for individuals, together with any associated software applications and websites (collectively the “ Services ”). These Terms form a contract between you and Clous Technology, SL, a Madrid company, and include the Terms of Service and important provisions for the resolution of disputes through arbitration. By using our Services, you agree to these Terms. 

If you reside in the European Economic Area (EEA), Switzerland or the United Kingdom, your use of the Services is governed by these Terms .

Our Business Terms govern your use of Clous Enterprise, our APIs, and our other business and developer services. 

Our Privacy Policy explains how we collect and use personal data. Although it is not part of these Terms, it is an important document that you should read.

About us
Clous is a company dedicated to the research and implementation of AI. Our mission is to ensure that artificial general intelligence benefits all humanity. To learn more about Clous, visit https://www.clous.app/about .

Registration and Access
Minimum age . You must be at least 13 years old or the minimum age required in your country to consent to use the Services. If you are under 18 years of age, you must obtain permission from your parent or legal guardian to use the Services. 

Record . You must provide us with accurate and complete information to register for an account to use our Services. You must not share your account credentials or make your account available to third parties, and you will be responsible for all activities that occur under your account. If you create an account or use the Services on behalf of another person or entity, you must be authorized to accept these Terms on behalf of such person or entity.

Use of Our Services
Permitted Actions . You may access and use our Services subject to your compliance with these Terms. When using our Services, you must comply with all applicable laws, as well as our Sharing and Posting Policy, Usage Policies and any other documentation, guidelines or policies that we make available to you.

Actions Not Allowed . You may not use our Services for any illegal, harmful or abusive activities. For example, you will not be able to:

Use our Services in a way that infringes, misappropriates or violates the rights of any person.

Modify, copy, rent, sell or distribute any of our Services.

Try or assist anyone in reverse engineering, decompiling or discovering the source code or underlying components of our Services, including our models, algorithms or systems (unless this restriction is prohibited by applicable law).

The automatic or programmatic extraction of data or Output (as that term is defined below).

State that the Output has been generated by humans when this has not been the case.

Interfere with or disrupt our Services, including circumventing any limit or restriction on the number of times you can send requests or messages to the server in a given period of time or circumvent any security protection or mitigation measures we put in our Services.

Use the results to develop models that compete with Clous.

Software. Our Services may allow you to download software such as mobile applications, which may be automatically updated to ensure you are using the latest version. Our software may include open source software that is governed by applicable licenses that we make available to you.

Corporate Domains. If you create an account using an email address owned by an organization (for example, your employer), that account may be added to the organization's business account with us, in which case we will provide you with notice so you can help. to facilitate the transfer of your account. Once your account is transferred, the organization administrator may control your account, including the ability to access the Content (as that term is defined below) and restrict or remove your access to the account. 

Thirdparty services . Our Services may include software, products or services from third parties (" Third Party Services ") and some parts of our Services, such as our navigation functionality, may include output from those services (" Third Party Output "). Third Party Services and Third Party Output are subject to their own terms and conditions and we are not responsible for them.

Feedback . We appreciate your feedback, and you agree to our use of it without restriction or compensation to you.

Content
Your Content. You may enter input into the Services (the "Input") and obtain output based on your Input (the "Output") through the Services. The Input and Output will be jointly referred to as "Content". You will be responsible for the Content and must ensure that it does not violate applicable laws or these Terms. You represent and warrant that you have all necessary rights, licenses and permissions to enter Input into our Services.

Ownership of Content. As between you and Clous, and to the extent permitted by applicable law, you (a) retain your ownership rights in the Input and (b) own the Output. Under these Conditions we transfer to you full ownership, interests and all rights that we have, if applicable, over the Output. 

Similarity of Content. Given the nature of our Services and artificial intelligence in general, the output may not be unique and other users may receive similar output through our Services. The transfer provided above does not extend to the output of other users or the Output of Third Parties.

Our Use of Content. We may use the Content to provide, maintain, develop and improve our Services, comply with applicable laws, enforce our terms and policies, and ensure the security of our Services. 

Voluntary Exclusion. If you do not want us to use your Content to train our models, you can opt out by following the instructions in this Help Center article. Please note that in some cases this may limit our Services' ability to best address your specific use case.

Accuracy. Artificial intelligence and machine learning are rapidly evolving fields of study. We are constantly working to improve our Services and make them more accurate, reliable, secure and beneficial. Given the probabilistic nature of machine learning, in some situations the use of our Services may generate Output that does not accurately reflect people, places or events. 

When using our Services, you understand and agree that:

Output may not always be accurate. Do not consider that the Output of our Services is the only source of truthful or factual information, nor a substitute for professional advice. 

You should evaluate the accuracy and appropriateness of the Output for your particular use case, including by conducting a human review, if applicable, before using or sharing the Output from the Services.

You must not use the Output relating to a person for any purpose that may have a significant impact or legal consequences for that person, for example, to make decisions about financial, educational or employment matters, decisions about housing and insurance, about legal matters or medical or other important decisions related to that person. 

Our Services may generate incomplete, incorrect or offensive Output that does not represent the views of Clous. If the Output refers to third-party products or services, this does not mean that the third party endorses or is affiliated with Clous.

Our Intellectual Property Rights
We and our related entities own all right, title and interest in and to the Services. You may only use our name and logo in accordance with our Brand Guidelines .

Payment Accounts
Billing. If you purchase any Service, you must provide us with complete and accurate billing information, including a valid payment method. For paid subscriptions, the fee will be automatically charged to your payment method on each agreed-upon periodic renewal until you cancel the subscription. You are responsible for paying all applicable taxes, and we will collect them from you when necessary. If payment cannot be completed, we may limit your account or suspend your access to our Services until we receive payment. 

Service Credits. You can pay for some Services in advance by purchasing service credits. All service credits are subject to our Service Credit Terms .

Cancellation. You can cancel your subscription at any time. Payments are non-refundable except where required by law. These Terms do not replace the application of any local laws regarding your cancellation rights.

Changes. We may change our prices at any time. If we increase the prices of our subscriptions, we will notify you at least 30 days in advance and any price increase will apply from your next renewal, so you can cancel if you do not agree with the price increase.

Termination and Suspension
Termination . You are free to stop using our Services at any time. We reserve the right to suspend or terminate your access to our Services or delete your account if we determine::

That has breached these Conditions or our Use Policies .

That we are obliged to do so to comply with the law.

That your use of our Services may put Clous, our users or any other person at risk or cause harm.

We may also cancel your account if it has been inactive for more than a year and you do not have a paid account. If we do, we will notify you in advance.

Resources . If you believe that we have suspended or canceled your account in error, you can appeal our decision by contacting our Support service.

Disruption of Services
We may decide to discontinue our Services, although if we do, we will notify you in advance and refund any prepaid and unused Services.

Exclusion of Guarantees
OUR SERVICES ARE PROVIDED “AS IS”. EXCEPT AS PROHIBITED BY LAW, NEITHER WE, NOR OUR AFFILIATES AND LICENSORS MAKE ANY WARRANTIES (EXPRESS, IMPLIED, STATUTORY OR OTHERWISE) REGARDING THE SERVICES, AND WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY, NON-INFRINGEMENT AND PEACEFUL USE AND ENJOYMENT, AS WELL AS ANY WARRANTY ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ACCURATE OR ERROR-FREE, OR THAT ANY CONTENT IS SECURE OR WILL NOT BE LOST OR ALTERED. 

YOU ACCEPT AND AGREE THAT ANY USE OF THE RESULTS FROM OUR SERVICE IS AT YOUR OWN RISK AND THAT YOU WILL NOT RELY ON THE RESULTS AS THE SOLE SOURCE OF TRUTHFUL OR FACTUAL INFORMATION, OR AS A SUBSTITUTE FOR PROFESSIONAL ADVICE.

Limitation of Liability
Neither we nor any of our affiliates or licenses will be responsible for any indirect, incidental, special, consequent or exemplary damage, including damage to losses of profits, good reputation, use or data or other losses, even if we have been warned OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY UNDER THESE TERMS SHALL NOT EXCEED THE GREATER OF THE AMOUNT YOU PAID FOR THE SERVICE GIVING RISE TO THE CLAIM DURING THE 12 MONTHS PRIOR TO THE LIABILITY ARISING AND ONE HUNDRED DOLLARS ($100). THE LIMITATIONS IN THIS SECTION ONLY APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.

Some countries and states do not allow the disclaimer of certain warranties or the limitation of certain damages, so some or all of the above terms may not apply to you, and you may have additional rights. In that case, these Terms only limit our liabilities to the maximum extent permitted by the laws applicable in your country of residence.

CLOUS AFFILIATES, SUPPLIERS, LICENSORS AND DISTRIBUTORS ARE THIRD PARTY BENEFICIARIES OF THIS SECTION.

Compensation
If you are a company or organization, to the extent permitted by law, you will indemnify and hold us, our affiliates and our staff harmless from any costs, losses, liabilities and expenses (including attorneys' fees) arising from third party claims arising from or related to your use of the Services and Content or any violation of these Conditions.

Dispute resolution
YOU AND CLOUS AGREE TO THE FOLLOWING BINDING ARBITRATION CLAUSES AND WAIVE ANY CLASS ACTION:

MANDATORY ARBITRATION . You and Clous agree to resolve any claim arising out of or related to these Terms or our Services, regardless of when the claim arose, even if before these Terms existed (a "Dispute"), through final and binding arbitration. You may opt out of arbitration within 30 days of account creation or any update to these arbitration terms within 30 days of the update taking effect by completing this form. If you opt out of an update, the latest set of agreed upon arbitration terms will apply. 

Informal Conflict Resolution . We would like to understand and try to resolve your concerns before taking formal legal action. Before either of us brings a claim against the other, we both agree to try to resolve the Dispute informally. You agree to do so by sending us a notification through this form. We will do this by sending you a notification to the email address associated with your account. If we are unable to resolve the Dispute within 60 days, either of us has the right to initiate an arbitration proceeding. Likewise, we both agree to attend a conciliation hearing, if either party requests one during this period. During this informal resolution process any statute of limitations will be suspended.

Arbitration Forum . If we are unable to resolve the dispute, either of us may initiate arbitration before the National Arbitration and Mediation ("NAM") under its Comprehensive Dispute Resolution Rules and Procedures and/or Supplementary Rules for Mass Arbitration Filings, as applicable. Clous will not seek attorneys' fees or costs in the arbitration unless the arbitrator determines your claim is frivolous. The activities described in these Terms involve interstate commerce and the Federal Arbitration Act will govern the interpretation and application of these arbitration terms and any arbitration. 

Arbitration procedure . The arbitration will be conducted by video conference if possible, but if the arbitrator determines that the hearing must be held in person, the location will be mutually agreed upon, in the county where you reside, or as determined by the arbitrator, unless applicable the group arbitration process. The arbitration will be conducted by a single arbitrator. The arbitrator will be a retired judge or an attorney licensed to practice law in the State of Spain. The arbitrator shall have exclusive authority to resolve any Dispute, except that the state or federal courts located in Madrid, Spain, shall have authority to determine any Dispute regarding the applicability, validity of class action waiver or requests for public injunctive relief, as set forth below. Neither party will disclose the amounts of any settlement offers to the arbitrator until after the arbitrator determines the final award, if any. The arbitrator has the authority to grant motions dispositive of all or part of any Dispute. 

Exceptions . This section does not require informal dispute resolution or arbitration of the following claims: (i) individual claims brought in small claims court; and (ii) injunctive or other equitable relief to stop unauthorized use or abuse of the Services or infringement or misappropriation of intellectual property.

WAIVER FROM INITIATING CLASS ACTIONS AND JURY TRIAL . You and Clous agree that Disputes must be brought only on an individual basis, and may not be brought as a plaintiff or class member in any class, consolidated, or representative proceeding. Class arbitrations, class actions, and representative actions are prohibited. Only individual repair is possible. The parties agree to separate and litigate in court any request for public injunctive relief after completion of arbitration for the underlying claim and all other claims. This does not prevent either party from participating in a collective agreement. You and Clous knowingly and irrevocably waive any right to a jury trial in any action, proceeding or counterclaim. 

Arbitration by Groups . If 25 or more claimants represented by the same or similar attorneys file arbitration claims raising substantially similar Disputes within 90 days of each other, then you and Clous agree that NAM will administer them in groups of up to 50 claimants each ("Class"), unless there are fewer than 50 claimants in total or after consolidation, which will comprise a single Class. NAM will administer each Class as a single consolidated arbitration with one arbitrator, one set of arbitration fees, and a hearing held by video conference or at a location determined by the arbitrator for each Class. If any part of this section is found invalid or unenforceable to a particular claimant or Class, it will be severed and arbitrated in individual proceedings.  

Divisibility . If any part of these arbitration terms is held illegal or unenforceable, the remainder will remain in effect, except that if a declaration of illegality or partial unenforceability would permit class arbitration, class action, or representative action, this entire dispute resolution section will be inapplicable in its entirety.

Copyright Claims
If you believe that your intellectual property rights have been infringed, please send a notification to the address below or complete this form. We may remove or disable Content that we believe violates or is alleged to be violating these Terms, and we will terminate the accounts of repeat violators where appropriate.

Clous Technology, SL
62, 6B
Madrid, Spain 28003

Any written claim of copyright infringement must include the following:

The electronic or physical signature of the person authorized to act on behalf of the copyright owner;

A description of the copyrighted work that you claim has been infringed;

A description of where the allegedly infringing material is located on our website so that we can locate it;

Your address, telephone number and email address;

A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and

A statement signed by you that the information in your notice is accurate and, under penalty of perjury, that you are the copyright owner or authorized to act on the copyright owner's behalf.

General conditions
Assignment. You may not assign or transfer any of your rights or obligations under these Terms and any attempt to do so will be void. We may assign our rights or obligations under these Terms to any affiliate, subsidiary, or successor in interest of any company associated with our Services.

Modification of these Conditions or Our Services. We are constantly working to develop and improve our Services. Accordingly, we may update these Terms or our Services from time to time. For example, we may modify these Terms or the Services due to:

Legislative or regulatory changes.

Security or protection reasons.

Circumstances beyond our reasonable control.

The introduction of changes in the ordinary development of our Services.

The need to adapt to new technologies.

We will notify you at least 30 days in advance of any changes to these Terms that may significantly harm you, either by email or by means of an in-product notification. All other changes will be effective as soon as we post them on our website. If you do not agree to the changes, you must stop using our Services.

Delay in Demanding Compliance with These Conditions. If we do not enforce a provision, we do not waive our right to do so later. Except as provided in the dispute resolution section above, if any part of these Terms is determined to be invalid or unenforceable, that part will be enforced to the maximum extent permitted and will not affect the enforceability of any other terms. .

Commercial Controls. You must comply with all applicable trade laws, including sanctions and export control laws. Our Services may not be used in or for the benefit of, or exported or re-exported (a) into any country or territory to which the U.S. has embargoed or (b) to any person or entity to which we are prohibited or restricted. doing business under applicable trade laws. Our Services may not be used for any end use prohibited by applicable trade laws, and your Input may not include any material or information that requires a government license for disclosure or export. 

Entire Contract. These Terms contain the entire Agreement between you and Clous relating to the Services and, except for any terms specific to the Services, supersede any prior or contemporaneous agreements between you and Clous.

Applicable Law. These Terms will be governed by the laws of Spain, excluding its conflict of law principles. Except as provided in the dispute resolution section above, all claims arising out of or related to these Terms will be brought exclusively in the federal or state courts located in Madrid, Spain.

            </p> 
        </div>
      </div>
      <Footer />
    </Layout>
  );
}
export default Terms;